alter table IP_ADDRESS drop constraint IP_ADDRESS_TYPE_FK;
alter table IP_ADDRESS_TO_SYSTEM drop constraint IP_ADDRESS_FK;
alter table IP_ADDRESS_TO_SYSTEM drop constraint SYSTEM_FK;
alter table NMAP_HOST drop constraint IP_ADDRESS_TO_SYSTEM_FK;
alter table NMAP_HOST drop constraint NMAPSCAN_FK;
alter table NMAP_HOST_SCRIPT drop constraint NMAP_HS_NMAP_HOST_FK;
alter table NMAP_HOST_SCRIPT drop constraint NMAP_HS_NMAP_SCRIPT_FK;
alter table NMAP_PORT drop constraint NMAP_PORT_NMAPSCAN_FK;
alter table NMAP_PORT drop constraint NMAP_HOST_FK;
alter table NMAP_PORT drop constraint PORT_FK;
alter table NMAP_PORT_SCRIPT drop constraint NMAP_PORT_FK;
alter table NMAP_PORT_SCRIPT drop constraint NMAP_SCRIPT_FK;
alter table NMAP_POST_SCRIPT drop constraint NMAP_POSTS_NMAP_SCRIPT_FK;
alter table NMAP_POST_SCRIPT drop constraint NMAP_POSTS_NMAPSCAN_FK;
alter table NMAP_PRE_SCRIPT drop constraint NMAP_PRES_NMAPSCAN_FK;
alter table NMAP_PRE_SCRIPT drop constraint NMAP_PRES_NMAP_SCRIPT_FK;
alter table NMAP_SSL_CIPHER drop constraint NMAP_SSL_TLS_PROTOCOL_FK;
alter table NMAP_SSL_CIPHER drop constraint SSL_TLS_CIPHER_FK;
alter table NMAP_SSL_ENUM_CIPHERS drop constraint NMAP_SEC_NMAP_PORT_FK;
alter table NMAP_SSL_ENUM_CIPHERS drop constraint NMAP_SEC_NMAP_SCRIPT_FK;
alter table NMAP_SSL_TLS_PROTOCOL drop constraint NMAP_SSL_ENUM_CIPHERS_FK;
alter table NMAP_SSL_TLS_PROTOCOL drop constraint SSL_TLS_PROTOCOL_FK;
alter table NMAPSCAN drop constraint SCAN_FK;
alter table PORT drop constraint PORT_SYSTEM_FK;
alter table SCAN drop constraint SCAN_SCAN_TYPE_FK;

drop sequence IP_ADDRESS_ID_SEQ;
drop sequence IP_ADDRESS_TO_SYSTEM_ID_SEQ;
drop sequence IP_ADDRESS_TYPE_ID_SEQ;
drop sequence NMAP_HOST_ID_SEQ;
drop sequence NMAP_HOST_SCRIPT_ID_SEQ;
drop sequence NMAP_PORT_ID_SEQ;
drop sequence NMAP_PORT_SCRIPT_ID_SEQ;
drop sequence NMAP_POST_SCRIPT_ID_SEQ;
drop sequence NMAP_PRE_SCRIPT_ID_SEQ;
drop sequence NMAP_SCRIPT_ID_SEQ;
drop sequence NMAP_SSL_CIPHER_ID_SEQ;
drop sequence NMAP_SSL_ENUM_CIPHERS_ID_SEQ;
drop sequence NMAP_SSL_TLS_PROTOCOL_ID_SEQ;
drop sequence NMAPSCAN_ID_SEQ;
drop sequence PORT_ID_SEQ;
drop sequence SCAN_ID_SEQ;
drop sequence SCAN_TYPE_ID_SEQ;
drop sequence SSL_TLS_CIPHER_ID_SEQ;
drop sequence SSL_TLS_PROTOCOL_ID_SEQ;
drop sequence SYSTEM_ID_SEQ;

drop table IP_ADDRESS;
drop table IP_ADDRESS_TO_SYSTEM;
drop table IP_ADDRESS_TYPE;
drop table NMAP_HOST;
drop table NMAP_HOST_SCRIPT;
drop table NMAP_PORT;
drop table NMAP_PORT_SCRIPT;
drop table NMAP_POST_SCRIPT;
drop table NMAP_PRE_SCRIPT;
drop table NMAPSCAN;
drop table NMAP_SCRIPT;
drop table NMAP_SSL_CIPHER;
drop table NMAP_SSL_ENUM_CIPHERS;
drop table NMAP_SSL_TLS_PROTOCOL;
drop table PORT;
drop table SCAN;
drop table SCAN_TYPE;
drop table SSL_TLS_CIPHER;
drop table SSL_TLS_PROTOCOL;
drop table SYSTEM;
